### ISSUE TITLE
How summary() outputs standardized coefficients and model fitting values

### ISSUE THREAD

**Issue by yihongfa** [Kss2k/modsem#1]
Like `summary(model,standardized = TRUE, fit.measures = TRUE, rsquare = TRUE)` in lavaan.

**Comment by Kss2k** [comment]
Thanks for the comment, but the feature isn't implemented yet. For the time being you can access the lavaan model directly by $lavaan. - So you can do something like 'lavaan::summary(modelObject$lavaan, ...)'.

**Comment by Kss2k** [comment]
Thanks for the comment, but the feature isn't implemented yet. For the time being you can access the lavaan model directly by $lavaan. - So you can do something like 'lavaan::summary(modelObject$lavaan, ...)'.
    It should now be possible to pass
